// Copyright (c) 2017-2021 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include <string.h>

#include "mfx_vaapi_debug.h"

#undef MFX_DEBUG_MODULE_NAME
#define MFX_DEBUG_MODULE_NAME "mfxvaapidebug"

#if MFX_DEBUG == MFX_DEBUG_YES && defined(LIBVA_SUPPORT)

MFX_DEBUG_DEFINE_VALUE_DESC_PRINTF(
  VAStatus,
  MFX_DEBUG_VALUE_DESC(VA_STATUS_SUCCESS),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_OPERATION_FAILED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ALLOCATION_FAILED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_DISPLAY),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_CONFIG),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_CONTEXT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_SURFACE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_BUFFER),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_IMAGE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_SUBPICTURE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ATTR_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_MAX_NUM_EXCEEDED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_PROFILE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_RT_FORMAT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNSUPPORTED_BUFFERTYPE),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_SURFACE_BUSY),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_FLAG_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_PARAMETER),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_RESOLUTION_NOT_SUPPORTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_UNIMPLEMENTED),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_SURFACE_IN_DISPLAYING),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_INVALID_IMAGE_FORMAT),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_DECODING_ERROR),
  MFX_DEBUG_VALUE_DESC(VA_STATUS_ERROR_ENCODING_ERROR))

#endif // #if MFX_DEBUG == MFX_DEBUG_YES && defined(LIBVA_SUPPORT)
